### PR TITLE
Set up MongoDB environment 

### PR DESCRIPTION
**Pull request by greenson**
Set up the MongoDB docker container  

- Usage: git checkout mongodb-env -> git pull -> vagrant destroy -> vagrant up -> vagrant ssh -> docker exec -it mongodb bash  
- Then you should be able to use the MongoDB interactive bash.

### CODE REVIEW

**Comment by greenson** [comment]
Please leave "LGTM" if you have reviewed and approved it.

**Comment by lhmartin** [comment]
LGTM

**Comment by Krystal-158** [comment]
LGTM

**Comment by silemie** [comment]
LGTM

**Pull request merged**
